[build]
builder = "NIXPACKS"
# Dockerfileを無視してNixpacksを強制使用
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10
